spring:
  application:
    name: manil

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      connectionInitSql: "SET search_path TO app, public"

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: app
        format_sql: true
        jdbc.time_zone: UTC

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: "never"

image:
  root-dir: /var/www/manil/uploads
  public-base-url: http://43.201.10.255/images/
  max-size-bytes: 10485760
  allowed-extensions: jpg,jpeg,png,webp

manil:
  gemini:
    api-key: ${GEMINI_API_KEY}
    base-url: https://generativelanguage.googleapis.com
    embed-model: gemini-embedding-001
    generate-model: gemini-2.5-flash-lite
    dim: 768
    connect-timeout-ms: 3000
    read-timeout-ms: 8000
  search:
    repo-top-k: 200
    result-top-n: 3
    weights:
      embedding: 0.55
      keywords: 0.15
      abstract-tags: 0.15
      filters: 0.10
      price: 0.05
    price:
        sigma: 10000
    penalties:
      category-mismatch: 0.05

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql.BasicBinder: WARN