name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

env:
  APP_DIR: /home/${{ secrets.EC2_USER }}/app
  JAR_NAME: app.jar

jobs:
  deploy:
    # Org 레포에서 오작동/오배포 방지: 포크 소유자일 때만 실행
    if: github.repository_owner == 'YOUR_GITHUB_USERNAME'
    runs-on: ubuntu-latest
    concurrency:
      group: manil-deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build jar (skip tests)
        run: ./gradlew clean bootJar -x test

      - name: Write SSH key
        run: |
          printf '%s' "${{ secrets.EC2_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Ensure app dir on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
              mkdir -p ${APP_DIR}"

      - name: Upload jar
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no \
            build/libs/*.jar ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ env.APP_DIR }}/${{ env.JAR_NAME }}

      - name: Restart service
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
              sudo systemctl restart manil && \
              sleep 3 && systemctl is-active manil"

      # (선택) 서버 안에서 헬스 체크
      - name: Health check on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
            ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "\
              curl -fsS http://localhost:8080/actuator/health || (journalctl -u manil -n 100 --no-pager; exit 1)"